import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import 'react-toastify/dist/ReactToastify.css';
import { Slide, ToastContainer } from 'react-toastify';
import ReduxProvider from "../redux/reduxProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KuraKani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-cream">
      <body className={` ${inter.className}`}>
        <ReduxProvider>
          <Providers>
            <ToastContainer
              position="top-right"
              theme="light"
              autoClose={4000}
              hideProgressBar
              closeOnClick
              transition={Slide}
            />
            {children}
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
